### ISSUE TITLE
Better method to derive bucket name from URI

### ISSUE THREAD

**Issue by markjschreiber** [awslabs/aws-java-nio-spi-for-s3#40]
The current method to determine a bucket name from a URI involves parsing the authority from the URI. https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/main/src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java#L58

This probably won't work for URIs that use S3 Access Points, S3 multiregion access points and possibly not s3 buckets on AWS Outposts or Snowball devices.

```[tasklist]
### Tasks
- [ ] Check Access Points
- [ ] Check MR access points
- [ ] Check Outposts
- [ ] Check Snowball devices
- [ ] Build unit test examples of all of the above
```

**Comment by stefanofornari** [comment]
in addtion, PR #43, parses for uri in the form of s3://[[key:secret]@endpoint]/bucket/resource

**Comment by stefanofornari** [comment]
This is going to be address with #30; I won't be able to check it with with mentioned tasks, hopefully @markjschreiber you can do it.

**Comment by markjschreiber** [comment]
We don't need to test against physical devices. The main thing is to check the specification of what the URI for any of the above would look like and if it is different from the normal S3 URI then ensure the logic to get the bucket name can account for this. The patterns for the URIs should all be available from the docs for these products.

**Comment by dannycjones** [comment]
> in addtion, PR #43 (former #32), parses for uri in the form of s3://[[key:secret@]endpoint]/bucket/resource

I'd recommend to have the S3 URI as only bucket and key for now.

Keep endpoint to configuration and credentials to configuration as well, if it cannot already be met by the [default credential provider chain](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain) which includes environment variable configuration.

**Comment by stefanofornari** [comment]
We have a problem with this approach... The FileSystem API provides a newFileSystem(URI, Map) but only getFileSystem(URI). When we cache the file system created in newFileSystem(), we have to use endpoint/bucket as key for the cache because we may have two file systems with same bucket name but on different endpoints. But if we do not have a way to give the endpoint to getFileSystem() we won't be able to retrieve the cached instance.

We could work around it ignoring S3_SPI_ENDPOINT passed in env, but then the following won't work:

```
Properties p = System.getProperties();
p.setProperty(S3_SPI_ENDPOINT, "http://endpoint1.com");

S3FileSystem fs = (S3FileSystem)FileSystems.newFileSystem("s3://foo/baa", env);
p.setProperty(S3_SPI_ENDPOINT, "http://endpoint2.com");
fs = (S3FileSystem)FileSystems.getFileSystem("s3://foo/baa"); -> will throw a FileSystemNotFound exception
```
Plus, System properties and environment variables are singleton in the JVM, making working with multiple file systems and in a multithreaded application a mess.

So... I think we should go back to the approach of having the endpoint on the URI. Or do you see other options?

**Comment by markjschreiber** [comment]
I don't think we should support a scenario where someone attempts to access the same bucket with two endpoints, or even two separate buckets with the same name using two endpoints. Environment variables are unique to a JVM as are things like AWS configurations done through profiles. This seems like an extreme edge case? I'm not sure it makes sense in the context of a generic SPI.

**Comment by stefanofornari** [comment]
Hi Mark, 
that is a very common scenario actually. Imagine you have two object stores and you mirror them for example. Or that given we are going not to have control on the name of the buckets, different people may run into cases where a bucket has the same name on many user's object store. Truly, this is a very basic scenario. Otherwise, it would be like you do not support having the same directory on two different FTP servers.

**Comment by stefanofornari** [comment]
actually, now that I think about it, we can not consider a bucket name unique even for S3 endpoints, as different accounts can potentially (and for sure) have buckets with the same name...

**Comment by markjschreiber** [comment]
Bucket names are globally unique across all accounts and regions. Collisions are not possible.

**Comment by stefanofornari** [comment]
That was an example, you can read it as "copy" and it would work as well. BTW what the users would or would not do is hard to predict and it is somehow debatable.
Maybe what I do not get is what's your alternative proposal to really support other endpoints keeping with the FileSystems semantic. So, again, just as an example, how would you implement differently the following:

`Files.copy(Paths.get("s3://sourceendpoint.io/mybucket/copyme.txt"), Paths.get("s3://destinationendpoint.io/mybucket"));`

**Comment by markjschreiber** [comment]
According to S3 URI rules `s3://sourceendpoint.io/mybucket/` refers to a bucket called `sourceendpoint.io` and not a bucket called `mybucket`. `mybucket/copyme.txt` is the key of the object.

**Comment by stefanofornari** [comment]
you are not answering the question mark, mine was pseudocode. ho can we achieve that simple copy operation in a alternative way?

**Comment by markjschreiber** [comment]
A copy from `bucket1` to `bucket1` with the same key is a no-op. A copy from `bucket1` with endpoint A to `bucket1` with endpointB is only possible if you have constructed different S3Clients.

As far as the SPI is concerned the URI is identical and there is no difference. There is no way you can tell Java that the path `s3://bucket/key` is different from `s3://bucket/key` even if you have two clients with two different endpoints because the S3 URI says nothing about endpoints. It would be like telling it that `file://foo/baa` is different from `file://foo/baa`. This is why you can't try to use a Java SPI to copy between providers where the bucket name is the same. To do something like that you need to go lower level and use S3 clients with different configurations and ideally not use s3 URIs.

Because a Java SPI can't distinguish the endpoint from the URI it has to be done via a client and you can realistically only have one client per bucket because the URI can't tell you which client to use.

The S3 URI pattern probably wasn't designed with service interoperability in mind.

**Comment by stefanofornari** [comment]
Then this project does not make any sense :) but likely I see it differently ;)

First, we could extend the s3 URI to non AWS services adding the endpoint:

s3://bucket1 <-- AWS S3 URI, nothing changes for AWS folks
s3://myservice.io/bucket1 <-- my service URI, an extended S3 URI, compliant with URI and NIO 

It is actually already implemented in my PR. Then it is up to the SPI provider to parse the URI accordingly and do the right things. Again, already implemented.

I would strongly recommend to accept the above, it makes everything smooth and straightforward for S3 compatible users.

But even if we say we want to stay strict on the URI representation (but please show me the benefits), the pattern can be:
```

Map<String, String> sourceEnv = new HashMap<>(), targetEnv = new HashMap<>();
sourceEnv.put("s3.spi.endpoint", "sourceendpoint.com"); targetEnv.put("s3.spi.endpoint", "targetendpoint.com");

FileSystem sourceFileSystem = FileSystems.newFileSystem("s3://bucket1", sourceEnv);
FileSystem targetFileSystem = FileSystems.newFileSystem("s3://bucket1", targetEnv);

Files.copy(sourceFileSystem.getPath("dir/blob.bin"), targetFileSystem.getPath("dir/blob.bin"));
```

et voilà. Again the core of this functionality is already implemented in the PR, although all file manipulation methods must be reviewed with this in mind (ie. we can not assume we can use a simple copyObject() ). It is uglier than using the full URI, but I could work with it, and we could even have both. Use the one in the URI if provided, otherwise pick it from the env parameter.

**Comment by stefanofornari** [comment]
@markjschreiber what do you think about the above? I'd like to progress with my project where I'd love to use this module to access S3 like repositories. So I need to understand if the effort I am putting has a chance to be merged or not. many thanks.

**Comment by markjschreiber** [comment]
I think it could work to have the URI interpreted in the context of a `Filesystem` instance. All URIs would need to start with `s3` because that is how the JVM figures out which SPI to use.

**Comment by stefanofornari** [comment]
Ok thanks! you can review that in the PR. I will keep updating it. I actually spotted a bug in the policy above: a bucket name can have dots in it, so we need to always specify the port when using the endpoint.

> All URIs would need to start with s3 because that is how the JVM figures out which SPI to use.
Yes, this for sure.
